---
# vars file for JenkinsUbuntu
jenkins_repo:  https://pkg.jenkins.io/debian-stable/jenkins.io.key
jenkins_port: 8080
java_version:  "default-jdk"
dir_dest : "/home/azureuser/"
system_user: "azureuser"
# vars file for kubectl

kubectl_version_url: "https://storage.googleapis.com/kubernetes-release/release/stable.txt"

kubectl_url: "https://storage.googleapis.com/kubernetes-release/release/{{ lookup('url', kubectl_version_url) }}/bin/linux/amd64/kubectl"

_kubectl_validate_certs:
  default: yes
  Debian: no

kubectl_validate_certs: "{{ _kubectl_validate_certs[ansible_os_family] | default(_kubectl_validate_certs['default']) }}"
