---
- name: use motd role playbook
  hosts: web
  become: true

  roles:
    - role: JenkinsUbuntu
      jenkins_port: 8080

# - name: Import role for Ubuntu
#   import_role:
#     name: JenkinsUbuntu
#   when: ansible_facts['ansible_os_family'] == 'Debian'

# - name: Import role for Centos
#   import_role:
#     name: JenkinsCentos
#   when: ansible_facts['ansible_os_family'] == 'RedHat'