---
- name: Update apt-get repo and cache
  apt:
     update_cache: yes
     force_apt_get: yes
     cache_valid_time: 3600

- name: Jenkins repository
  apt_key:
    url: "{{jenkins_repo}}"
    state: present
  become: true

- name: Adding jenkins to source list
  apt_repository:
    repo: "deb https://pkg.jenkins.io/debian-stable binary/"
    state: present
  become: true

- name: Check if Java is already installed
  command: java -version
  ignore_errors: true
  register: java_version

- name: Install Java
  apt:
    name: "{{java_version}}"
    state: present
    update_cache: yes

- name: Check if jenkins is already installed
  command:  jenkins --version
  ignore_errors: true
  register: jenkins_version

- name: ensure jenkins is installed
  apt:
    name: jenkins
    update_cache: yes
  when: jenkins_version.rc != 0  
  become: true

- name: ensure jenkins is running
  service:
    name: jenkins
    state: started 
    enabled: yes

- name: Get Jenkins password
  shell: cat /var/lib/jenkins/secrets/initialAdminPassword
  changed_when: false
  register: result
  when: jenkins_version.rc != 0  

- name: Password to "Unlock Jenkins"
  debug:
    var: result.stdout
  when: jenkins_version.rc != 0  

- name: Check if kubect  is already installed
  command:   kubectl version
  ignore_errors: true
  register: kubectl_version

- name: Install kubectl
  ansible.builtin.get_url:
    url: "{{ kubectl_url }}"
    dest: /usr/bin/kubectl
    mode: "755"
    validate_certs: "{{ kubectl_validate_certs }}"
  when : kubectl_version.rc != 0



- name: Include   Docker tasks
  ansible.builtin.include_tasks:
    file: "./roles/JenkinsUbuntu/tasks/DockerTasks.yml"

- name: copy kube Config File
  copy:
    src: C:\\Users\\abdelali\\.kube\\config
    dest: "{{dir_dest}}"



